version: '3.8'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
    depends_on:
      - postgres
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'
  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"

volumes:
  postgres:
  composer:
  redis: